### ISSUE TITLE
#OffTopic - Forest world generator -Need help :)

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/InstantTree#1]
Im trying make world generator of biomes, but im very noob and dont know how fix it.

The error is :

12.11 10:18:04 [Server] Server thread/INFO Disabling Forest1 v1
12.11 10:18:04 [Server] Server thread/CRITICAL Error: "Call to undefined method Generator::addGenerator()" (EXCEPTION) in "/Forest.phar/src/generator/Main" at line 12
12.11 10:18:04 [Server] Server thread/INFO Enabling Forest1 v1

My email is wrrs07@gmail.com

Thank you ^^

**Comment by inxomnyaa** [comment]
The only thing i figured out is you maybe didnt add 'use pocketmine/level/Generator'

**Comment by WiliRodin** [comment]
Ñ


Enviado desde mi Samsung Mobile de Claro

-------- Mensaje original --------
De: Dan <notifications@github.com> 
Fecha:2016/11/14  03:11 AM  (GMT-05:00) 
A: thebigsmileXD/InstantTree <InstantTree@noreply.github.com> 
CC: Wili Rodin <paypalwilirodin@gmail.com>, Author <author@noreply.github.com> 
Asunto: Re: [thebigsmileXD/InstantTree] #OffTopic - Forest world generator
  -Need help :) (#1) 

The only thing i figured out is you maybe didnt add 'use pocketmine/level/Generator' —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
